name: h3
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  collection: ^1.15.0
  ffi: ^1.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.17.10
  build_runner: ^2.1.0
  build_test: ^2.1.3


flutter:
  plugin:
    androidPackage: com.leavetrail.h3
